baseURL = "https://nickolaskraus.org"
languageCode = "en-us"
title = "Nickolas Kraus"
author = "Nickolas Kraus"
canonifyurls = true
theme = "black-and-light-2"

pygmentsStyle       = "tango"
pygmentsCodeFences  = true

googleAnalytics = "UA-115911814-1"

[params]
  siteName = "Nickolas Kraus"
  dateFormat = "January 2, 2006"

[[params.social]]
  email = "nickhkraus@gmail.com"
  garmin = "https://connect.garmin.com/modern/profile/6b22dde1-552e-45d4-9608-c5fe6b6d3ea4"
  github = "https://github.com/NickolasHKraus"
  instagram = "https://www.instagram.com/nickolashkraus"
  linkedin = "https://linkedin.com/in/nickolas-kraus"
  rss = "https://nickolaskraus.org/index.xml"
  stackoverflow = "https://stackoverflow.com/users/9659079/nickolashkraus"
  strava = "https://www.strava.com/athletes/23618436"
  twitter = "https://twitter.com/NickolasHKraus"

[[menu.main]]
  name = "About"
  url  = "/about"
[[menu.main]]
  name = "Articles"
  url  = "/articles"
[[menu.main]]
  name = "Projects"
  url  = "/projects"
[[menu.main]]
  name = "Resume"
  url  = "/resume.pdf"
[[menu.main]]
  name = "Transcripts"
  url  = "/transcripts"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
